import assert from 'node:assert/strict'
import test from 'node:test'
import { buildAnalyticsReport } from '../frontend/src/utils/analyticsReport.js'
import { buildAnalyticsWorkbook } from '../frontend/src/utils/analyticsWorkbook.js'

const reportInput = {
  reportScope: 'Main - Brgy 7',
  reportPeriod: '2026-09-01 to 2026-09-30',
  generatedAt: new Date('2026-10-01T08:30:00+08:00'),
  logoUrl: 'https://laundry.test/assets/Rectangle.png',
  stats: { totalRevenue: 1500, totalExpenses: 400, profit: 1100, avgOrderValue: 750, totalOrders: 2 },
  payments: [{ id: 'deposit' }, { id: 'balance' }, { id: 'second-order' }],
  descriptiveData: [{ date: 'Sep 2026', revenue: 1500, expenses: 400 }],
  forecastData: [{ forecastDate: '2026-10-02', predicted: 800, predictedOrders: 3, confidence: 'high' }],
  forecastModel: 'Gemini-assisted forecast',
  forecastSource: 'Generated by Gemini AI',
  decisionSupportSource: 'Generated by Gemini AI',
  aiInsights: [{ title: 'Inventory Readiness', description: 'Restock detergent before the forecast peak.' }],
  operationalSummary: {
    services: [{ name: 'Wash & Fold', orders: 2, revenue: 1300, weightKg: 18, quantity: 2 }],
    branches: [{ name: 'Main - Brgy 7', orders: 2, revenue: 1500 }],
    staffPerformance: [{ name: 'Maria Santos', created: 2, completed: 1 }],
    lowStockItems: [{ name: 'Detergent', branch: 'Main - Brgy 7', current_stock: 2, minimum_stock: 5, unit: 'kg' }],
    repeatCustomers: 1,
    completedOrders: 1,
    averageTurnaroundHours: 4.5,
  },
}

const report = buildAnalyticsReport(reportInput)

test('corporate analytics CSV contains report controls and complete management sections', () => {
  assert.match(report.csv, /I&C LAUNDRY MANAGEMENT PERFORMANCE REPORT/)
  assert.match(report.csv, /REPORT CONTROL/)
  assert.match(report.csv, /SERVICE PERFORMANCE/)
  assert.match(report.csv, /STAFF PRODUCTIVITY/)
  assert.match(report.csv, /INVENTORY ATTENTION LIST/)
  assert.match(report.csv, /RECOMMENDED MANAGEMENT ACTIONS/)
  assert.match(report.csv, /distinct non-cancelled orders/i)
  assert.equal(report.csvFilename, 'IC-Laundry-Management-Report-2026-10-01.csv')
})

test('print report is I&C branded and includes governance and sign-off content', () => {
  assert.match(report.printHtml, /I&amp;C Laundry/)
  assert.match(report.printHtml, /https:\/\/laundry\.test\/assets\/Rectangle\.png/)
  assert.match(report.printHtml, /Management Performance Report/)
  assert.match(report.printHtml, /Executive Performance Summary/)
  assert.match(report.printHtml, /Inventory Items Needing Attention/)
  assert.match(report.printHtml, /Important Notes About the Numbers/)
  assert.match(report.printHtml, /Reviewed by/)
  assert.match(report.printHtml, /not counted again when the customer pays the balance/i)
  assert.match(report.printHtml, /What Management Should Know/)
})

test('spreadsheet export is a styled multi-sheet I&C management workbook', async () => {
  const workbook = await buildAnalyticsWorkbook({ ...reportInput, logoUrl: '' })
  assert.deepEqual(workbook.worksheets.map((sheet) => sheet.name), [
    'Management Summary',
    'Financial Trend',
    'Operations',
    'Inventory & Forecast',
    'Recommended Actions',
  ])
  const summary = workbook.getWorksheet('Management Summary')
  assert.equal(summary.getCell('A1').value, 'I&C LAUNDRY MANAGEMENT REPORT')
  assert.equal(summary.getCell('A1').fill.fgColor.argb, '123F5C')
  assert.equal(summary.views[0].state, 'frozen')
  const bytes = await workbook.xlsx.writeBuffer()
  assert.ok(bytes.byteLength > 10000)
})

